Part13 authorization
peresvetjke/stackoverflow pull request #10
Opened 2021-12-15 07:54 UTC by peresvetjke

2021-12-16 09:15 UTC, vkurennov requested changes

2021-12-16 09:15 UTC, vkurennov commented on app/controllers/active_storage/attachments_controller.rb
> +  before_action :authenticate_user!
вот это всегда первым должно идти, иначе  если юзер не залогинен, нет смысла что-либо загружать. и авторизация в такой последовательности можэет неверно работать, т.к. юзер должен быть уже загружен перед авторизацией

2021-12-16 09:15 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    before_action :authenticate_user!, only: %i[create destroy mark_best]
опять же, аутентификация всегда самая первая в контроллере, потом уже все остальное

2021-12-16 09:15 UTC, vkurennov commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
тут надо сделать обработчик и для других форматов. редирект имеет смысл только в html-формате, а в js и json yадо вовзращать 403 статус и его уже на клиенте обрабатывать

2021-12-16 09:15 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!, except: %i[show index]
это в начало контроллера

2021-12-16 09:15 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +  before_action :authenticate_user!, only: :accept
в начало контроллера

2021-12-16 09:15 UTC, vkurennov commented on app/models/ability.rb
> +      votable.author_id != @user.id
используй метод проверки автора из модели User

2021-12-17 08:50 UTC, peresvetjke commented on app/controllers/active_storage/attachments_controller.rb
> +  before_action :authenticate_user!
> вот это всегда первым должно идти

исправил (здесь и далее). 
в тестах тоже выделил - у меня раньше аутентификация фактически в рамках авторизации проходила )

2021-12-17 08:50 UTC, peresvetjke commented on app/controllers/answers_controller.rb
>    before_action :authenticate_user!, only: %i[create destroy mark_best]
исправлено

2021-12-17 08:50 UTC, peresvetjke commented on app/controllers/application_controller.rb
> +  rescue_from CanCan::AccessDenied do |exception|
исправлено:
[app/controllers/application_controller.rb /](https://github.com/peresvetjke/stackoverflow/blob/ce0061e9a7feb8fdaab079384078e8446f13141c/app/controllers/application_controller.rb)
[app/assets/javascripts/shared/alerts.js](https://github.com/peresvetjke/stackoverflow/pull/10/files#diff-2b096ae7b6682e02395afa25647aad49e34107e21a3341efa17bd08f43922abf)

2021-12-17 08:51 UTC, peresvetjke commented on app/controllers/questions_controller.rb
> +  before_action :authenticate_user!, except: %i[show index]
исправлено

2021-12-17 08:51 UTC, peresvetjke commented on app/controllers/votes_controller.rb
> +  before_action :authenticate_user!, only: :accept
исправлено

2021-12-17 08:51 UTC, peresvetjke commented on app/models/ability.rb
> +      votable.author_id != @user.id
исправлено

2021-12-17 09:12 UTC, vkurennov approved these changes

2021-12-17 09:12 UTC, vkurennov commented on app/controllers/application_controller.rb
> +    if current_user.nil?
за это отвечает devise, именно поэтому аутентификация и должна ставиться первой в контроллере. так что это лишнее и не в том месте, здесь нужна обработка только кейса неавторизованного действия

2021-12-18 05:10 UTC, peresvetjke commented on app/controllers/application_controller.rb
> +    if current_user.nil?
убрал, спасибо

2021-12-18 05:10 UTC, merged