Part6 acceptance tests
peresvetjke/stackoverflow pull request #3
Opened 2021-11-12 11:21 UTC by peresvetjke

2021-11-13 10:50 UTC, vkurennov requested changes

2021-11-13 10:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    question = answer.question
это лишнее можно было смело оставить answer.question, где нужно

2021-11-13 10:50 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if current_user == answer.author
1. такая проверка не оптимальная, т.к. приходится делать запрос к базе для загрузки ассоциации и тратить память, лучше сравнивать по author_id, чтобы этого избежать
2. такая проверка много где будет нужна, стоит вынести ее в метод `User#author_of?` и использовать этот метод для проверки. И не забудь тесты модели на него написать

2021-11-13 10:50 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user == question.author
Замени на вызов `User#author_of?`

2021-11-13 10:50 UTC, vkurennov commented on app/views/layouts/application.html.erb
>    </head>
лейаут тоже стоит на slim перевести

2021-11-13 10:50 UTC, vkurennov commented on app/views/questions/show.html.slim
> +- if current_user == question.author
Замени на вызов `User#author_of?`

2021-11-13 10:50 UTC, vkurennov commented on app/views/questions/show.html.slim
> +      td = current_user == a.author ? button_to('Delete answer', answer_path(a), method: :delete, data: { confirm: "Are you sure?" }) : ""
1. не используй тернарный оператор в видах, он очень громоздко здесь смотрится и усложняет чтение. тем более, что ветки с "else" тут нет. Замени на обычный if
2. вот здесь такая проверка на автора (не по id) приводит к классической проблеме n+1 запроса: например, если у нас 10 ответов, то их все мы за один запрос грузим еще в контроллере, а потом для каждого ответа еще грузим автора, итого делая 10 запросов по одному на каждый ответ. Итого 11 запросов. Сравнение по  id решает эту проблему.

2021-11-13 10:50 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +          expect { delete :destroy, params: { id: answer } }.to change(Answer, :count).by(0)
ну мы же не говорим "изменилось на ноль", а говорим "не изменилось", вот и пиши `not_to change`

2021-11-13 10:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { post :create, params: { question: attributes_for(:question) } }.to change(Question, :count).by(0)
`not_to change`

2021-11-13 10:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          expect { post :create, params: { question: attributes_for(:question, :invalid) } }.to change(Question, :count).by(0)
`not_to change`

2021-11-13 10:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          other_user = create(:user)
зачем переменная тут? объедини в одну строку: `login(create(:user))`

2021-11-13 10:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(0)
`not_to change`

2021-11-13 10:50 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        it "deletes all question's answers from db" do
это лишнее и не относится к поведению контроллера, это мы проверяем в тестах модели через тест опции dependent

2021-11-13 10:50 UTC, vkurennov commented on spec/features/answers/create_spec.rb
> +      fill_in "Your answer", :with => "My answer"
используй всегда "новый" стиль записи хешей, не через hachrocket (=>), а через двоеточие

2021-11-13 10:50 UTC, vkurennov commented on spec/features/answers/create_spec.rb
> +      expect(page).to have_content("You need to sign in or sign up before continuing")
у методов dsl, обычно скобки не принято ставить, а вот у своих методов или методов библиотек - наоборот надо ставить скобки

2021-11-13 10:50 UTC, vkurennov commented on spec/features/answers/create_spec.rb
> +    scenario "tries to create answer with non-unique body" do
не нужно все валидации проверять, это мы в тестах модели должны делать, здесь достаточно проверить, что система в принципе сообщает об ошибках пользователю, поэтому достаточно на одной любой валидации проверить

2021-11-13 10:50 UTC, vkurennov commented on spec/features/answers/create_spec.rb
> +      expect(page).to have_text("Answer has been succesfully posted")
это доказывает лишь наличие сообщения на странице, но при этом нет проверки, что сам ответ на странице появился, а это критически важно

2021-11-13 10:50 UTC, vkurennov commented on spec/features/answers/destroy_spec.rb
> +      expect(find(:xpath, "//*[contains(text(), '#{other_answer.body}')]/parent::tr")).to have_no_button("Delete answer")
через xpath не стоит тестировать, во-первых, сложно для чтения и понимания, во-вторых, если селектор ошибочный, то тест пройдет, но не факт, что он будет верный. поэтому лучше как-то "железобетонно" задать нужный участок страницы для проверки, чтобы не было сомнений в правильности

2021-11-13 10:50 UTC, vkurennov commented on spec/features/answers/destroy_spec.rb
> +      expect(page).to have_content("Your answer has been deleted")
тут стоит перед удалением проверить, что ответ есть на странице, а после - что его нет

2021-11-13 10:50 UTC, vkurennov commented on spec/features/questions/create_spec.rb
> +      expect(page).to have_text("Question has been successfully created")
нужно проверить, что вопрос появился на странице

2021-11-13 10:50 UTC, vkurennov commented on spec/features/questions/create_spec.rb
> +    scenario "tries to create question with blank body" do
достаточно одной проверки на валидацию

2021-11-13 10:50 UTC, vkurennov commented on spec/features/questions/destroy_spec.rb
> +      expect(page).to satisfy("Question and its answers deleted") do |page|
круто, но не увлекайся сильно такими штуками - могут усложнять код, лучше писать максимально просто и понятно и использовать несколько expect

2021-11-13 10:50 UTC, vkurennov commented on spec/rails_helper.rb
> +  # cleaner
а вот это лишнее, т.к. начиная с 5х рельс, это встроенная фича

2021-11-14 04:23 UTC, peresvetjke commented on app/controllers/answers_controller.rb
> +    question = answer.question
Строчка мне тоже не нравится, но если ее удалить, то как определить куда редиректить?
Удаляя ответ, мы "забываем" про то, на какой вопрос вернуться:
Couldn't find Question with 'id'=63, где 63 - id удаляемого _ответа_ (http://localhost:3000/answers/63)
Поэтому временно сохраняю answer.question.
Если не так тебя понял, поправь пожалуйста.

P.S. Кажется, проблема уйдет, когда переведем на ajax.

Спасибо

2021-11-14 04:23 UTC, peresvetjke commented on spec/features/answers/destroy_spec.rb
> +      expect(page).to have_content("Your answer has been deleted")
После удаления - добавил.
А перед удалением проверяем - именно так находится строка, где нужно нажать delete:
`page.find(:xpath, "//*[contains(text(), '#{answer.body}')]/parent::tr").click_button("Delete answer")`

2021-11-14 04:24 UTC, peresvetjke commented on spec/features/questions/destroy_spec.rb
> +      expect(page).to satisfy("Question and its answers deleted") do |page|
Честно говоря, не знал, что можно делать несколько expect )
Поправил, спасибо!

2021-11-14 04:24 UTC, peresvetjke commented on spec/rails_helper.rb
> +  # cleaner
В определенный момент тесты стали падать из-за не уникальных названий (несмотря на наличие sequence).
Проверил бд (в тестовой ENV) - 20 объектов. Удивился, почистил вручную и продолжил работать дальше. Через некоторое время проблема снова возникла - уже 3 объекта )) при перезапуске тестов кол-во не меняется. В общем воспроизвести добавление я не смог.

То есть если правильно понимаю, у меня эта встроенная фича отрабатывает не вполне корректно (почему не знаю). После установки клинера проблема ушла.

2021-11-14 16:06 UTC, merged